#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
#yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

# global settings
yabai -m config window_placement second_child

yabai -m config auto_balance off

yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5

yabai -m config layout bsp
yabai -m config top_padding     10
yabai -m config bottom_padding  10
yabai -m config left_padding    10
yabai -m config right_padding   10
yabai -m config window_gap      10

# ignore these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Ivory$" manage=offs
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Microsoft Remote Desktop$" manage=off
yabai -m rule --add app="^WezTerm$" manage=off

# Stop teams popups from being managed
yabai -m rule --add title="$| Microsoft Teams" manage=off

# mouse support
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus off
yabai -m c config focus_follows_mouse off

